{{- range $name, $service := .Values.services }}
{{ if not $service.volumes }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $name }}"
  labels:
    stack.okteto.com/name: "{{ include "stack.fullname" $ }}"
    stack.okteto.com/service: "{{ include "stack.fullname" $ }}-{{ $name }}"
    app.kubernetes.io/component: "{{ $name }}"
    {{- include "stack.labels" $ | nindent 4 }}
spec:
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      stack.okteto.com/name: "{{ include "stack.fullname" $ }}"
      stack.okteto.com/service: "{{ include "stack.fullname" $ }}-{{ $name }}"
  template:
    metadata:
      labels:
        stack.okteto.com/name: "{{ include "stack.fullname" $ }}"
        stack.okteto.com/service: "{{ include "stack.fullname" $ }}-{{ $name }}"
    spec:
      containers:
        - name: "{{ $name }}"
          image: "{{ $service.image }}"
          {{ if $service.command }}
          command:
          {{ if eq (typeOf $service.command) "string" }}
            - sh
            - -c
            - {{ $service.command }}
          {{ else }}
            {{- range $command := $service.command }}
            - {{ $command }}
            {{ end }}
          {{ end }}
          {{ end }}
          {{ if $service.args }}
          args:
            {{- range $arg := $service.args }}
            - {{ $arg }}
            {{ end }}
          {{ end }}
          {{ if $service.ports }}
          ports:
            {{- range $port := $service.ports }}
            - containerPort: {{ $port }}
            {{ end }}
          {{ end }}
          {{ if $service.env }}
          env:
            {{- range $env := $service.env }}
            - name: {{ (splitn "=" 2 $env)._0 }}
              value: {{ (splitn "=" 2 $env)._1 }}
            {{ end }}
          {{ end }}
---
{{- end }}
{{- end }}
