{{- range $name, $service := .Values.services }}
{{ if $service.ports }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}"
  labels:
    stack.okteto.com/name: "{{ include "stack.fullname" $ }}"
    stack.okteto.com/service: "{{ include "stack.fullname" $ }}-{{ $name }}"
    app.kubernetes.io/component: "{{ $name }}"
    {{- include "stack.labels" $ | nindent 4 }}
  {{ if $service.public }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
  {{ end }}
spec:
  type: ClusterIP
  ports:
  {{- range $port := $service.ports }}
  - port: {{ $port }}
  {{ end }}
  selector:
    stack.okteto.com/name: "{{ include "stack.fullname" $ }}"
    stack.okteto.com/service: "{{ include "stack.fullname" $ }}-{{ $name }}"
---
{{- end }}
{{- end }}
